# 기존에 있던 프로젝트 이름
spring.application.name=demo

# ─────────────────────────────────────────
# 여기에 내가 필요한 설정을 추가로 적어 나가는 것입니다!
# ─────────────────────────────────────────
spring.datasource.url=jdbc:mysql://localhost:3306/testDB?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true